
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions: null
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-flinkoperator-k8s-io-v1beta2-flinkcluster
  failurePolicy: Fail
  name: mflinkcluster.flinkoperator.k8s.io
  rules:
  - apiGroups:
    - flinkoperator.k8s.io
    apiVersions:
    - v1beta2
    operations:
    - CREATE
    - UPDATE
    resources:
    - flinkclusters
  sideEffects: null

---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions: null
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-flinkoperator-k8s-io-v1beta2-flinkcluster
  failurePolicy: Fail
  name: vflinkcluster.flinkoperator.k8s.io
  rules:
  - apiGroups:
    - flinkoperator.k8s.io
    apiVersions:
    - v1beta2
    operations:
    - CREATE
    - UPDATE
    resources:
    - flinkclusters
  sideEffects: null
