{{- if .Values.serviceAccount.flinkoperator.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "flink-operator.serviceAccountName" . }}
  namespace: {{ .Values.flinkOperatorNamespace.name }}
  annotations:
{{- with .Values.serviceAccount.flinkoperator.annotations }}
{{ toYaml . | indent 4 }}
{{- end }}
  labels:
    {{- include "flink-operator.labels" . | nindent 4 }}
{{- end }}
