# permissions for end users to view flinkclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: flinkcluster-viewer-role
rules:
- apiGroups:
  - flinkoperator.k8s.io
  resources:
  - flinkclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - flinkoperator.k8s.io
  resources:
  - flinkclusters/status
  verbs:
  - get
