apiVersion: v1
kind: Service
metadata:
  name: controller-manager
  labels:
    app: flink-operator
spec:
  ports:
  - port: 8443
    name: https
  clusterIP: None
  selector:
    app: flink-operator
