name: Publish Docker image
on:
  release:
    types: [published]
jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    env:
      DOCKER_REPO: ghcr.io/spotify/flink-operator
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Prepare
        id: prep
        run: |
          echo ::set-output name=image::${DOCKER_REPO}:${GITHUB_REF/refs\/tags\//}
      - name: Login to Github container registry
        uses: docker/login-action@v1.1.1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Push image
        run: make operator-image push-operator-image
        env:
          IMG: ${{ steps.prep.outputs.image }}
      - name: Tag latest
        run: docker tag ${{ steps.prep.outputs.image }} ${DOCKER_REPO}:latest
      - name: Push latest
        run: docker push ${DOCKER_REPO}:latest
